### ISSUE TITLE
ドメインの建て方のドキュメントを書く

### ISSUE THREAD

**Issue by totegamma** [totegamma/concurrent#43]

**Comment by fono09** [comment]
適切な場所ができたら私が加筆するという言質

https://concurrent.world/message/0f7e8842-f6b7-4d2c-a678-3645ad02d7f2@CC9e5D3D77Cc07BFf90a8c5AD96902fD7e9ce4a3DC

**Comment by totegamma** [comment]
squareの方に書いてくださったのでこちらはclose
ありがとうございました 🙇‍♂️
