### ISSUE TITLE
docs/config/gatway.yamlのwebfingerはapbridgeに向いていないといけない？

### ISSUE THREAD

**Issue by fono09** [totegamma/concurrent#60]
https://github.com/totegamma/ccworld-ap-bridge/blob/master/cmd/activitypub/main.go#L143

/.well-known/webfinger
/.well-known/nodeinfo

を処理できるのはapbridgeであるため。

https://github.com/totegamma/concurrent/blob/develop/docs/config/gateway.yaml#L23
ここを修正する必要がありそう。

**Comment by totegamma** [comment]
これ完全に開発中の名残ですね... apbridgeが正しそうです🙏
